steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true", "-D\"spring-boot.run.profiles\"=prod","appengine:deploy"]