steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true", "-Dspring.profiles.active=dev" , "-Darg_database_pass=${_SECRET_PASSWORD}", "appengine:deploy"]