steps:
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["test"]
  - name: maven:3-jdk-11
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true", "-D\"spring-boot.run.profiles\"=prod", "-D\"spring-boot.run.jvmArguments\"=\"-DARG_DATABASE_PASS=${_SECRET_PASSWORD}\"","appengine:deploy"]